apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: abdulmajeed951/healthcare-abdul:1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  type: ClusterIP  # Service type correctly placed here
  selector:
    app: healthcare
  ports:
  - port: 80
    targetPort: 8082

